#!/usr/bin/env bash

echo "Reloading Firefox..."

osascript -e 'set previous_app to path to frontmost application as text
              activate application "Firefox"
              tell application "System Events" to keystroke "r" using command down
              activate application previous_app'
